# [phases.setup] removed to allow auto-detection of Node.js version

[phases.install]
cmds = ["npm install --prefer-offline --no-audit"]

[phases.build]
cmds = ["npx prisma generate", "next build"]

[start]
cmd = "npx prisma migrate deploy && npm start"
